name: CI

on:
  push:
  pull_request:

env:
  DATABASE_URL: https://fake.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: actions/npm@v1
        with:
          command: install

      - name: Typecheck
        uses: actions/npm@v1
        with:
          command: run typecheck

      - name: Lint
        uses: actions/npm@v1
        with:
          command: run lint
